import { v4 as uuidv4 } from "uuid";

export const thead = [
  { value: "index", label: "ردیف", sortable: false, show: true },
  {
    value: "edit",
    label: "ویرایش",
    sortable: false,
    show: true,
  },
  {
    value: "code",
    label: "کد",
    sortable: false,
    show: true,
  },
  {
    value: "fullName",
    label: "نام طرف حساب",
    sortable: false,
    show: false,
  },
  { value: "phoneNumber", label: "تلفن", sortable: false, show: false },
  { value: "mobile", label: "موبایل", sortable: false, show: false },
  { value: "saleMan", label: "فروشنده", sortable: false, show: false },
  { value: "buyer", label: "خریدار", sortable: false, show: false },

  { value: "intermediator", label: "واسطه", sortable: false, show: false },
  { value: "investor", label: "سرمایه گذار", sortable: false, show: false },
  {
    value: "badAccount",
    label: "بد حساب",
    sortable: false,
    show: false,
  },
  { value: "nationalId", label: "کد/شناسه ملی", sortable: false, show: false },
  { value: "economicCode", label: "کد اقتصادی", sortable: false, show: false },
  { value: "active", label: "فعال", sortable: false, show: false },
  {
    value: "introduceDate",
    label: "تاریخ معرفی",
    sortable: false,
    show: false,
  },
  { value: "province", label: "استان", sortable: false, show: false },
  { value: "city", label: "شهر", sortable: false, show: false },
  {
    value: "salesIntermediary",
    label: "واسطه فروش",
    sortable: false,
    show: false,
  },
  { value: "commission", label: "پورسانت", sortable: false, show: false },
  { value: "ceoName", label: "نام مدیرعامل", sortable: false, show: false },
  { value: "birthDate", label: "تاریخ تولد", sortable: false, show: false },
  { value: "job", label: "شغل", sortable: false, show: false },
  { value: "fax", label: "فکس", sortable: false, show: false },
  { value: "preCode", label: "پیش کد", sortable: false, show: false },
  { value: "email", label: "ایمیل", sortable: false, show: false },
  { value: "website", label: "وبسایت", sortable: false, show: false },
  { value: "creditLimit", label: "سقف اعتبار", sortable: false, show: false },

  //   { value: "actions", label: "", sortable: false, show: true },
];

export const tableBody = Array.from({ length: 50 }, (_, index) => ({
  index: index + 1,
  id: uuidv4(),
  edit: "ویرایش",
  code: 1000 + index,
  fullName: [
    "علی محمدی",
    "رضا کریمی",
    "سارا احمدی",
    "مهدی حسینی",
    "نگار موسوی",
    "محمد رضایی",
    "زهرا عباسی",
    "امیر جعفری",
    "فاطمه قاسمی",
    "حسین اکبری",
  ][index % 10],
  phoneNumber: `021${10000000 + index}`,
  mobile: `0912${100000 + index}`,
  porsant: Math.floor((63 * index) % 10),
  saleMan: ["احمدی", "کریمی", "موسوی", "حیدری"][index % 4],
  buyer: index % 2 === 0 ? "بله" : "خیر",
  intermediator: index % 3 === 0 ? "بله" : "خیر",
  investor: index % 4 === 0 ? "بله" : "خیر",
  badAccount: index % 7 === 0 ? "بله" : "خیر",
  address: `تهران، خیابان ${index + 1}`,
  personType: index % 2 === 0 ? "حقیقی" : "حقوقی",
  nationalId: `${1000000000 + index}`,
  economicCode: `${2000000000 + index}`,
  active: index % 5 === 0 ? "غیرفعال" : "فعال",
  introduceDate: `1403/0${(index % 9) + 1}/15`,
  postalCode: `${1111111111 + index}`,
  province: ["تهران", "اصفهان", "فارس", "خراسان"][index % 4],
  city: ["تهران", "شیراز", "مشهد", "اصفهان"][index % 4],
  salesIntermediary: ["ندارد", "شرکت الف", "شرکت ب"][index % 3],
  commission: `${(index + 1) * 100000} تومان`,
  ceoName: ["محمدی", "کریمی", "احمدی", "حسینی"][index % 4],
  birthDate: `136${index % 10}/05/12`,
  job: ["برنامه نویس", "حسابدار", "مدیر فروش", "طراح"][index % 4],
  fax: `021${22220000 + index}`,
  preCode: `0${21 + (index % 10)}`,
  activityType: ["تجاری", "خدماتی", "تولیدی"][index % 3],
  email: `user${index + 1}@example.com`,
  website: `www.site${index + 1}.com`,
  creditLimit: `${(index + 1) * 5000000} تومان`,
}));

export const iranCities = [
  "تهران",
  "مشهد",
  "اصفهان",
  "شیراز",
  "تبریز",
  "کرج",
  "قم",
  "اهواز",
  "کرمانشاه",
  "رشت",
  "ارومیه",
  "زاهدان",
  "یزد",
  "همدان",
  "بندرعباس",
  "اردبیل",
  "ساری",
  "قزوین",
  "بوشهر",
  "سنندج",
];
